sudo: required

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.29.0

rvm:
  - 2.7

services:
  - docker

before_script: 
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.29.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - cd redmine

script:
  - docker-compose up -d